export const users = [
    {id: 1, name:"Umarali Imomaliyev", status: "BS", phoneNum: "+998999999999", address: "Uzbekistan, Tashkent", job: "Software enginer"},
    {id: 2, name:"Ollomurodov Olamgir", status: "CS", phoneNum: "+998999999999", address: "Uzbekistan, Samarqand", job: "Frontend Developer"},
    {id: 3, name:"Ahrorbek Ibodullayev", status: "BA", phoneNum: "+998999999999", address: "Uzbekistan, Navoi", job: "1C"},
    {id: 4, name:"Dilshodbek Rahimboyev", status: "BA", phoneNum: "+998999999999", address: "Uzbekistan, Namangan", job: "Designer"},
    {id: 5, name:"Obid Kenjaev", status: "AC", phoneNum: "+998999999999", address: "Uzbekistan, Tashkent", job: "3D Modeller"},
    {id: 6, name:"Khamdam Jumanov", status: "CC", phoneNum: "+998999999999", address: "Uzbekistan, Farg'ona", job: "Fullstack developer"},
    {id: 7, name:"Azimjon", status: "AC", phoneNum: "+998999999999", address: "Uzbekistan, Xorazm", job: "Backend developer"},
    {id: 8, name:"Mahliyo Juraeva", status: "BA", phoneNum: "+998999999999", address: "Uzbekistan, Xorazm", job: "AI developer"},
    {id: 9, name:"Omonova Gulhayo", status: "AC", phoneNum: "+998999999999", address: "Uzbekistan, Samarqand", job: "Animator"},
    {id: 10, name:"Matyoqubov Firdavs", status: "AC", phoneNum: "+998999999999", address: "Uzbekistan, Surxondaryo", job: "Frontend developer"},
    {id: 11, name:"Sultonov Husanboy", status: "AC", phoneNum: "+998999999999", address: "Uzbekistan, Nukus", job: "Tester"},
    {id: 12, name:"Ernazarov Muhammadnazar", status: "AC", phoneNum: "+998999999999", address: "Uzbekistan, Andijon", job: "SMM Manager"},
    {id: 13, name:"Jafar Meliboyev", status: "AC", phoneNum: "+998999999999", address: "Uzbekistan, Tashkent", job: "Marketolog"},
]